### ISSUE TITLE
Dude

### ISSUE THREAD

**Issue by qaiik** [VillainsRule4000/8Ball#1]
You seem to be forking a lot of people's repositories, and not really doing much with them. Are you sure that you aren't just stealing peoples code, and pretending it is yours. I noticed you've starred my blkt-reader, and I hope you don't copy it.

**Comment by VillainsRule4000** [comment]
@qaiik Very true, when I fork something, it's sometimes a mental note to come back to it later, or to delete it soon after. Your Blooket repository has NOT been copied ANYWHERE. This specific one was going to get stylesheets.
